name: mix_deps
description: Run `mix deps.get` and cache dependencies.
branding:
  icon: 'arrow-down'
  color: 'purple'

inputs:
  erlang-version:
    description: Erlang version to use
    required: true
    type: string
  elixir-version:
    description: Elixir version to use
    required: true
    type: string
  path:
    description: Path to the Mix project
    required: false
    type: string
    default: .

runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v3
      id: cache-restore
      with:
        path: |
          ${{ inputs.path }}/_build
          ${{ inputs.path }}/deps
        key: ${{ runner.os }}-erlang-${{ inputs.erlang-version }}-elixir-${{ inputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-erlang-${{ inputs.erlang-version }}-elixir-${{ inputs.elixir-version }}-mix-
    - run: mix deps.get
      if: steps.cache-restore.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.path }}
      shell: bash
    - run: mix deps.compile
      if: steps.cache-restore.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.path }}
      shell: bash
    - uses: actions/cache/save@v3
      id: cache-save
      with:
        path: |
          ${{ inputs.path }}/_build
          ${{ inputs.path }}/deps
        key: ${{ runner.os }}-erlang-${{ inputs.erlang-version }}-elixir-${{ inputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
      if: steps.cache-restore.outputs.cache-hit != 'true'
